# Pre-commit hooks for NORSAIN Design Diagrams Template
# See https://pre-commit.com for more information

repos:
  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        files: \.(md|mmd|yaml|yml|json)$
      - id: end-of-file-fixer
        files: \.(md|mmd|yaml|yml|json)$
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=500']  # Diagrams can be larger
      - id: check-case-conflict
      - id: check-yaml
        files: \.(yaml|yml)$
      - id: check-json
        files: \.json$
      - id: mixed-line-ending
        fix: true

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        args: ["--config", ".markdownlint.json"]
        files: "\\.md$"

  # Mermaid diagram validation
  - repo: local
    hooks:
      - id: validate-mermaid
        name: Validate Mermaid diagrams
        entry: |
          bash -c '
          if command -v mmdc >/dev/null 2>&1; then
            find docs/diagrams -name "*.mmd" -exec sh -c "
              echo \"Validating \$1\"
              mmdc -i \"\$1\" -o /tmp/test.svg --configFile docs/mermaid-theme.json >/dev/null 2>&1 || {
                echo \"❌ Mermaid validation failed for \$1\"
                exit 1
              }
            " _ {} \;
            echo "✅ All Mermaid diagrams valid"
          else
            echo "⚠️  mmdc not found, skipping Mermaid validation"
          fi
          '
        language: system
        files: docs/diagrams/.*\.mmd$
        pass_filenames: false

  # Check for binary files in docs/diagrams
  - repo: local
    hooks:
      - id: no-binary-files
        name: No binary files in diagrams directory
        entry: |
          bash -c '
          binary_files=$(find docs/diagrams -type f \( -name "*.png" -o -name "*.jpg" -o -name "*.jpeg" -o -name "*.gif" -o -name "*.svg" \) 2>/dev/null)
          if [ -n "$binary_files" ]; then
            echo "❌ Binary files found in docs/diagrams/:"
            echo "$binary_files"
            echo "💡 Binary files should be generated by CI, not committed"
            exit 1
          else
            echo "✅ No binary files in diagrams directory"
          fi
          '
        language: system
        files: docs/diagrams/
        pass_filenames: false

  # Check Mermaid theme usage
  - repo: local
    hooks:
      - id: check-mermaid-theme
        name: Check Mermaid theme usage
        entry: |
          bash -c '
          for file in docs/diagrams/*.mmd docs/diagrams/*/*.mmd 2>/dev/null; do
            if [ -f "$file" ]; then
              if ! head -5 "$file" | grep -q "%%{init:"; then
                echo "❌ Missing theme initialization in $file"
                echo "💡 Add %%{init: { \"theme\": \"base\", \"themeVariables\": { ... }}}%% at the top"
                exit 1
              fi
            fi
          done
          echo "✅ All Mermaid files have theme initialization"
          '
        language: system
        files: docs/diagrams/.*\.mmd$
        pass_filenames: false
